name: Publish Image to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:

  build_and_publish:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "0.26.2" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Set lowercase owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/pkl-cli:latest
